### ISSUE TITLE
could you please upload a sample wav&TextGrid?

### ISSUE THREAD

**Issue by feelins** [monikaUPF/PyToBI#1]
I want to know how to annotate the wav file to use this project.

**Comment by monikaUPF** [comment]
Thanks for your interest in PyToBI.
To run the toolkit and get automatic prosody annotation you need a wav file and a transcription of that file with word segmentations in TextGrid format. I am attaching a sample TextGrid with automatic word alignments obtained using the Montreal Forced Aligner toolkit https://montreal-forced-aligner.readthedocs.io/en/latest/. 

Due to data protection issues, I am afraid I cannot share the associated wav file with the associated speech sample.
[spk2f_002_sample.zip](https://github.com/monikaUPF/PyToBI/files/4680607/spk2f_002_sample.zip)
