### ISSUE TITLE
Unable to run module04.praat

### ISSUE THREAD

**Issue by nkyadati** [monikaUPF/PyToBI#2]
I was using the tool for a short french phrase and am stuck at the module04.praat. I have the following error:
Script line 110 not performed or completed:
« plusObject: phones$ »
Script “/Users/to147971/PycharmProjects/prosody/PyToBI-master/module04.praat” not completed.
Praat: script command <<module04.praat /Users/to147971/PycharmProjects/prosody/audio/ s249_locuteur4_cas1>> not completed.

I have a wav file and the corresponding TextGrid file with two tiers - words & phones

Could you please help me?

**Comment by monikaUPF** [comment]
It seems that the problem is with the phones tier. Could you please make sure your word and phones tier are interval tiers?

Alternatively, if you can pass me the files that are causing issues to reproduce the error I'd probably get a closer ideas on what is wrong and be able to provide better help.

**Comment by nkyadati** [comment]
Thank you for your reply Monika. The phones tier is indeed an interval tier. I am attaching the files - audio and the textgrid here.
https://drive.google.com/drive/folders/1iZ81NCCCJZRTv08EXvXEy-Z7wGVxz4ty?usp=sharing

Looking forward to hear from you.

**Comment by monikaUPF** [comment]
Hi again,

There were several issues regarding the "TextGrid" you were using as well as some bugs I've already fixed in the code.

- The extension of your file is .txt instead of .TextGrid
- It started with an interval that included a label rather than with an empty interval, so that phone was not correctly recognized
- There were some encoding utf-8 issues as you were using symbols like ipa and # symbol
I've uploaded to your shared folder the TextGrid created from the file you sent me that I've tested on the updated code.

Finally, remember that you must download and place Praat in the praatScripts folder in this repository. 
You may want to pull the latest changes from this repo as I have updated the documentation  and checked some bugs as well.

Thanks for your patience and your interest in PyToBI.

Best regards,

Monika

**Comment by nkyadati** [comment]
Hello Monika,

Thank you for your quick responses. I tried what you suggested after pulling the latest version of the code, but still I run into the following error: 
Error: The command "Set interval text:" does not return anything; not assigned to the string variable "labw$".
Script line 310 not performed or completed:
« labw$ = Set interval text: 5, w, labeltextw$ »

Were you able to generate the output textgrid on your side? If so, could you please send me the textgrid, while I try to resolve the errors. I would really appreciate that. Thanks again!

**Comment by monikaUPF** [comment]
Hi again,

I've uploaded to your Drive all files generated by PyToBI including the result TextGrid.
Remember I run the code with the textgrid I crreated that includes only asci characters (also uploaded to your Drive).

Best,
M.

**Comment by nkyadati** [comment]
Thanks a lot for your help Monika 👍
